# Generated by Django 4.2.1 on 2023-05-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Prioridad baja'), ('N', 'Prioridad normal'), ('H', 'Prioridad alta')], default='N', max_length=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='tasks.subject', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Título'),
        ),
    ]
